DATA:
  IMG_W: 512
  IMG_H: 256
  VAL_BATCH_SIZE: 16
MODEL:
  TYPE: swin
  NAME: traffic-diversified
  DROP_PATH_RATE: 0.2
  FEATURE_SIZE: 2048
  SWIN:
    IN_CHANS: 3
    EMBED_DIM: 128
    DEPTHS: [2, 2]
    NUM_HEADS: [16,32]
    WINDOW_SIZE: 16
    PATCH_SIZE: 4
    PATCH_H: 4
    PATCH_W: 8
    AVG_POOL: False
SAVE_FREQ: 10
TRAIN:
  EPOCHS: 400
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.0e-5
  CLIP_GRAD: 0.0
  TRIPLET_SELECTION: diversified
  TRIPLET_ENABLE: True
  PBOUNDS: [100,100,100,100,100,100,100,100]
  NBOUNDS: [2250,1800,1600,1400,1200,1000,800]
  SWITCH: [0,100,150,200,250,300,350]
  LOAD_MAT: True
  MARGIN: 0.10
  CUDA: "cuda:0"
  TRIPLET_WEIGHT: 10.0
AMP_OPT_LEVEL: "O0"
